export const sponsorsBig = [
  {
    src: "./sponsors/big/dorigoni.webp",
    alt: "Dorigoni",
    width: 1000,
    height: 100,
    backgroundColor: "white",
  },
  {
    src: "./sponsors/big/cova.webp",
    alt: "Cova",
    width: 100,
    height: 100,
    backgroundColor: "white",
  },
  {
    src: "./sponsors/big/giacomelli.jpg",
    alt: "Giacomelli",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/angelo.PNG",
    alt: "Angelo",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/bioelettrica.webp",
    alt: "Bioelettrica",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/generali.webp",
    alt: "Generali",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/devigili.webp",
    alt: "Devigili",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/alpenos.jpg",
    alt: "Alpenos",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/franzoi.webp",
    alt: "Franzoi",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/zanella.webp",
    alt: "Zanella",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/nolo.webp",
    alt: "Nolo",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/dallago.jpeg",
    alt: "Dallago",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/battan.webp",
    alt: "Battan",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/conad.webp",
    alt: "Conad",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/enterprise.webp",
    alt: "Enterprise",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/pegaso.jpg",
    alt: "Pegaso",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/elettrica.webp",
    alt: "Elettrica",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/ecotrentino.webp",
    alt: "Ecotrentino",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
  {
    src: "./sponsors/big/SPORTLIFEE.webp",
    alt: "Sportlife",
    width: 100,
    height: 100,
    backgroundColor: "transparent",
  },
];
